CREATE TABLE IF NOT EXISTS Inventory (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,
    publication_date DATE NOT NULL,
    isbn  VARCHAR(10) UNIQUE NOT NULL
);
